version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "02:00"
    timezone: "Europe/Madrid"
  commit-message:
    prefix: "chore"
    prefix-development: "chore-dev"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - "jacanales"
  assignees:
  - "jacanales"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "03:00"
    timezone: "Europe/Madrid"
  commit-message:
    prefix: "chore"
    prefix-development: "chore-dev"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - "jacanales"
  assignees:
  - "jacanales"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "04:00"
    timezone: "Europe/Madrid"
  commit-message:
    prefix: "chore"
    prefix-development: "chore-dev"
    include: "scope"
  open-pull-requests-limit: 10
  reviewers:
  - "jacanales"
  assignees:
  - "jacanales"
  
