name-template: 'v$RESOLVED_VERSION ðŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  # What's Changed
  $CHANGES
categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'type: feature'
      - 'type: enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'type: fix'
      - 'type: bugfix'
      - 'type: bug'
  - title: 'ðŸ§° Maintenance'
    label: 'type: chore'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
  - title: 'Breaking'
    label: 'type: breaking'
version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'
      - 'type: chore'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'