addons:
  sonarcloud:
    organization: "jacanales"
    token:
      secure: "0rwq39+HMpohVwR2fNwr2bOQD3otWBYKMxma4gHqLVqAcGOGsVR0GS0Gl8tkVIndntU0y61KhSZac328rqEtzeRwTIegIddPOUCyykoL1B3Ti7CegHXT/XI48rujl4WftoLlStb3mm0A9V6l9TBKDmuREeZCYFCVskrxgy6mPW014vCVzpIyAhqPKQhC+iAgABwS+Z8rBnJoIcPdXbx9o9qUhGMu/mQDbrmizPvqdQBRXkqE00+ARglIV8kFtkCCtLi0KnwI+O7NKnNIOaglxAbphOY9f8NALiH/Z81j9kUxw+ESSzX6vNI2EddL3+NI7eLl64wE4i9+FNjgsNK+8AOM0WVd9jhIlcbcEGRmeAzIyzT54gg+gE9JCrcqMfUvun96XpKHtJIrMVffd6jj/mAJISDVA1FOGdP4nqWJR7sNxvEohVqW3WkpG9McrwhOg1cAoybiq0dXS45BGPtVeBasDLUcIyPzjS97fYcOKb7h7P4/MKAbVkcrwgA/VLxhkgWhmfWyRQ6cOor8hdcvs+RPHQQ6tXS+F3yL8tD2nwwP3SedzYgS+cqiPSgaby1ZDwud51JxTz70qZz1PKPgls4laJsjQpbnNP+xZm/r7g2fb6Wqimrm5TJXUvJZ/RDcOhuXlmdYCIgHxu//eLaVdXqlAJ2N2L1Hl9+wo3/FDto="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner