version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    steps:
      - checkout
      - run:
          name: Update composer
          command: sudo composer self-update --2
      - run:
          name: Install dependencies and build project
          command: composer install
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud