name: Check Conventional Commits
on: pull_request
jobs:
  commits:
    runs-on: ubuntu-latest
    steps:
      - name: hqprs
        uses: Namchee/conventional-pr@v0.2.1
        with:
          access_token: ${{ secrets.ACTION_COMMITS }}