name: Check Conventional Commits
on:
  pull_request:
    branches:
      - !mergify/jacanales/config-update
      - !dependabot/**
jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Commitsar check
        uses: aevea/commitsar@v0.20.2
